#! /bin/sh
# Copies a file or directory, displaying a progress bar during the transfer.

if [ $# -ne 2 ]; then
	echo "usage: $0 <source> <destination>"
	exit
fi

if [ -f "$1" ]; then # file-to-file or file-to-dir
	bar "$1" "$2"
elif [ -d "$1" ]; then # recursive directory copy
    SIZE=$(du -sb "$1" | awk '{print $1}')
	mkdir -p "$2"
    (cd "$1" && tar -cf - .) | bar -s $SIZE | (cd "$2" && tar -xBpf -)
else
	echo "Error: '$1' is not a valid file or directory"
fi
