#!/bin/sh
# Adapted from http://tldp.org/LDP/abs/html/sample-bashrc.html

if [ $# -eq 0 ]; then
	echo "Usage: extract <archive file(s)>"
	return
fi

for file in "$@"; do
	if [ -f "$file" ]; then
	case "$file" in
		*.tar)		tar xvf "$file"		;;
		*.tar.bz2)	tar xvjf "$file"	;;
		*.tbz2)		tar xvjf "$file"	;;
		*.tar.gz)	tar xvzf "$file"	;;
		*.tgz)		tar xvzf "$file"	;;
		*.tar.xz)	tar xvJf "$file"	;;
		*.txz)		tar xvJf "$file"	;;
		*.7z)		7z x "$file"		;;
		*.bz2)		bunzip2 "$file"		;;
		*.gz)		gunzip "$file"		;;
		*.rar)		unrar x "$file"		;;
		*.xz)		xz -d "$file"		;;
		*.Z)		uncompress "$file"	;;
		*.zip)		unzip "$file"		;;
		*)			echo "'$file' cannot be extracted. Unknown archive format."
	esac
	else
		echo "'$file' is not a valid file!"
	fi
done
